name: zabbix_sender
description: A simple zabbix_sender.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hprose: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
