name: zabbix_sender
description: A simple zabbix_sender.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
  # hprose: any

dev_dependencies:
  test: ^1.16.8
